apiVersion: v1
kind: Secret
metadata:
  name: dbvars
type: Opaque
stringData:
  password: {{PASSWORD}}
  database: {{DATABASE}}
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_DATABASE 
      valueFrom:
        secretKeyRef:
          name: dbvars   
          key: database      
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbvars  
          key: password   