apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: | 
    server {
        listen 80;
        location / {
            return 200 "OK";
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
